### ISSUE TITLE
layout option for portfolio-type term does not work with WP 4.4+

### ISSUE THREAD

**Issue by NicktheGeek** [copyblogger/genesis-portfolio-pro#18]
WP 4.4 introduced term meta so Genesis switched to support the new term meta logic. The layout setting check for the term meta is currently using the old method of checking the term meta setting. This needs to be updated to use the `get_term_meta()` function

**Comment by dreamwhisper** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Genesis Portfolio Pro](https://trello.com/c/l4QIUKcN/9-genesis-portfolio-pro)

**Comment by nickcernis** [comment]
This change seems to have broken the layout of Portfolio Type archive pages.

### Master branch
(body class always contains 'full-width-content', regardless of the Type's layout setting):

<img width="1095" alt="portfolio_types_flowers" src="https://user-images.githubusercontent.com/647669/29660234-b1cbb52a-88b8-11e7-848d-887eb4a5b71d.png">

### release/1.1 branch
(body class contains no genesis layout classes regardless of Type layout settings):

<img width="1312" alt="portfolio_types_flowers" src="https://user-images.githubusercontent.com/647669/29660275-cffae6ec-88b8-11e7-8865-1396124e0954.png">

<img width="976" alt="edit_portfolio_type_ _wp_test_ _wordpress" src="https://user-images.githubusercontent.com/647669/29660304-e6a7b5fa-88b8-11e7-9ce8-fee325e5060b.png">

<img width="1023" alt="theme_settings_ _wp_test_ _wordpress" src="https://user-images.githubusercontent.com/647669/29660342-077ff422-88b9-11e7-8483-d2ede01133ac.png">

### Suggested fix
`$layout` always gets a value of 'true' instead of the expected layout string, due to the assignment of $opt within the ternary:

~~~php
$term   = $wp_query->get_queried_object();
$layout = $term && isset( $term->term_id ) && $opt = get_term_meta( $term->term_id, 'layout', true ) ? $opt : __genesis_return_full_width_content();
~~~

Either of these options fix the layout issue:

~~~php
$term = $wp_query->get_queried_object();
$opt = get_term_meta( $term->term_id, 'layout', true );
$layout = $term && isset( $term->term_id ) && $opt ? $opt : __genesis_return_full_width_content();
~~~

~~~php
$term = $wp_query->get_queried_object();
if ( $term && isset( $term->term_id ) ) {
	$opt = get_term_meta( $term->term_id, 'layout', true );
}

return $opt && ! is_null( $opt ) ? $opt : 'full-width-content';
~~~

Also noting the label on the Type layout setting for the default setting is not quite accurate:

<img width="1039" alt="edit_portfolio_type_ _wp_test_ _wordpress" src="https://user-images.githubusercontent.com/647669/29662898-cd1ec8d2-88c0-11e7-9801-755090339948.png">

Selecting that does not use the site's default layout; it uses a full-width layout.

Haven't yet checked if we can filter that, but perhaps use another label if we can: “Default full-width layout for portfolio archives.”

**Comment by NicktheGeek** [comment]
@nickcernis opted for putting a bracket around the ternary operation. The reason I'm running it this way is if the function to get the term object failed then the term_id wouldn't be available. The checks preceding setting the option variable make sure that it doesn't generate errors when it gets to that point. If it fails any of those is should use the default and call it a day, so for simplicity in the code it can/should be part of the ternary.

The brackets prevent it from getting the wrong assignment by picking up "true" or "false" instead of the ternary assigned values. It's interesting that there must be a difference in PHP handling this because when I tested this it worked correctly. So if this doesn't solve the issue in the environment you are testing in, I'll need to use something less streamlined. If it does fail can you let me know the version of PHP you have running?

**Comment by nickcernis** [comment]
Confirmed: the layout now works. Thanks!

> there must be a difference in PHP handling this because when I tested this it worked correctly.

WP/PHP Coding Standards flag assignments within if statements or ternaries. It could be for the reason you highlight there (and because it's harder to read).

<img width="1019" alt="taxonomy-portfolio-type_php_ _wptest" src="https://user-images.githubusercontent.com/647669/29667957-50818402-88d6-11e7-88b0-3d4b92236711.png">

(Screenshot from VS Code with the phpcs extension.)
